# Makefile generic - Sources

#
# Construye una lista de archivos fuente (FILES) y de archivos objeto (OBJS)
# a partir del contenido de SRCDIR.
#
# The main file name.
MAINSRC = $(SRCDIR)$(BINARY)$(MAINSUF)

TEMP = $(wildcard $(SRCDIR)*.pas)
ifeq ($(strip $(TEMP)),)
$(error ERROR: No source code found at $(SRCDIR))
endif
SRCFILES = $(TEMP)
OBJFILES = $(addprefix $(OBJDIR),$(addsuffix $(OBJSUF), $(basename $(notdir $(TEMP) ) ) ) )
