# Makefile generic - Sources

#
# Builds the list of source files and object files for each bynary type.
#

# The main file name.
MAINSRC = $(SRCDIR)$(BINARY)$(MAINSUF)

# Program files.
SRCFILES = $(wildcard $(SRCDIR)*.pas)
ifeq ($(strip $(SRCFILES)),)
$(error ERROR: No source code found at $(SRCDIR))
endif
